Updating repo to adhere to repo standards
opentok/opentok-video-embed-demo pull request #4
Opened 2020-04-29 01:31 UTC by MichaelJolley

Includes:

- Updated README.md to include branding change image
- Updated README.md to define additional support options
- Added CODE_OF_CONDUCT.md

2020-04-29 04:36 UTC, msach22 commented on README.md
> +const express = require("express");
We shouldn't update these to double quotes. This might be a default from your editor. Could you please revert this back to single quotes?

2020-04-29 04:36 UTC, msach22 requested changes
Please see inline comments

2020-06-05 02:59 UTC, MichaelJolley commented
Ugh. @msach22 you're right. I think I had a VS Code extension that was doing that.  Should be cleaned up now.

2020-11-09 11:47 UTC, pardel approved these changes

2020-11-13 21:46 UTC, merged